### ISSUE TITLE
Invisible characters and Indentation guides aren't handled

### ISSUE THREAD

**Issue by adamellsworth** [michalsnik/snik-syntax#2]
![screen shot 2017-06-02 at 1 28 14 pm](https://cloud.githubusercontent.com/assets/7034617/26743618/61b311f8-4797-11e7-86b2-2def58bd2f10.png)

- [x] Indentation guides
- [x] Tabs/Spaces
- [x] EOL

**Comment by michalsnik** [comment]
Hey @adamellsworth, thanks for pointing this. It's now fixed in `snik-syntax@v1.1.1`.
